@host = http://localhost:7071
@instanceId = 34fff3b40d114817ba148f3778c91dc8

### Check status
GET {{host}}/runtime/webhooks/durabletask/instances/{{instanceId}}

### Simple: Start workflow
POST {{host}}/api/workflows/Simple
Content-Type: application/json

{ }

### OrderFulfillment: Start workflow
POST {{host}}/api/workflows/OrderFulfillment
Content-Type: application/json

{
  "orderId": "ord-3",
  "customerId": "cust-1",
  "customerEmail": "test@example.com",
  "correlationId": "corr-v2-001",
  "lineItems": [
    { "lineItemId": "li-1", "productId": "prod-1", "quantity": 2 }
  ]
}

### Generic: Approve
POST {{host}}/api/events/{{instanceId}}/ApprovalDecision
Content-Type: application/json

{
  "decision": "approved",
  "decisionMaker": "manager",
  "decisionTimestamp": "2026-05-03T12:00:00Z"
}

### Generic: Decline
POST {{host}}/api/events/{{instanceId}}/ApprovalDecision
Content-Type: application/json

{
  "decision": "declined",
  "decisionMaker": "director",
  "decisionTimestamp": "2026-05-03T12:00:00Z"
}


### RemoteProcessing: Start workflow
POST {{host}}/api/workflows/RemoteProcessing
Content-Type: application/json

{
  "orderId": "ord-3",
  "customerId": "cust-1",
  "customerEmail": "test@example.com",
  "correlationId": "corr-v2-001",
  "lineItems": [
    { "lineItemId": "li-1", "productId": "prod-1", "quantity": 2 }
  ]
}


### Generic: OrderProcessed
POST {{host}}/api/events/{{instanceId}}/OrderProcessed
Content-Type: application/json

{
  "status": "Succeeded",
  "processingTimeSeconds": 17
}


### LoopUntilFound: Start workflow
POST {{host}}/api/workflows/LoopUntilFound
Content-Type: application/json

{
  "siteUrl": "https://build.microsoft.com/en-US/sessions?search=hanselman&sortBy=relevance",
  "prompt": "Extract the full schedule for Scott Hanselman ('Hanselman') from this page, and only return success if it shows that he is presenting at least one session."
}
